# Generated by Django 5.0.4 on 2024-04-11 13:46

import app_userseller.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_userseller",
            "0003_alter_sellerprofile_managers_sellerprofile_groups_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="code",
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="device_token",
            field=models.CharField(
                default=1, max_length=100, verbose_name="токен от ios/android"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="email_or_phone",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="surname",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="username",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="password",
            field=models.CharField(
                max_length=128,
                validators=[app_userseller.validators.validate_password_strength],
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seller_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
