# Generated by Django 5.0.4 on 2024-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(default=1, upload_to="usual/profiles/"),
            preserve_default=False,
        ),
    ]
