# Generated by Django 5.0.4 on 2024-04-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_recommendations", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendations",
            name="product",
            field=models.ManyToManyField(to="product.product"),
        ),
    ]
