# Generated by Django 5.0.3 on 2024-03-11 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="chatsupport",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="chatsupport",
            name="user",
        ),
        migrations.RemoveField(
            model_name="messagesupport",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="messagesupport",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="messagesupport",
            name="sender",
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("date_added",)},
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="message",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="message",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="message",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="rooms", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="app_chat.room",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SupportService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("instagram_link", models.URLField()),
                ("whatsapp_link", models.URLField()),
                ("facebook_link", models.URLField()),
                ("telegram_token", models.CharField(max_length=50)),
                ("telegram_chat_id", models.CharField(max_length=15)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="ChatSupport",
        ),
        migrations.DeleteModel(
            name="MessageSupport",
        ),
    ]
