# Generated by Django 5.0.3 on 2024-03-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_chat", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SupportService",
        ),
    ]
