# Generated by Django 5.0.3 on 2024-03-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_chat", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
