# Generated by Django 5.0.3 on 2024-03-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
