# Generated by Django 5.0.3 on 2024-03-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0002_customuser_auth_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="auth_token",
            new_name="auth_token_access",
        ),
        migrations.AddField(
            model_name="customuser",
            name="auth_token_refresh",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
